### ISSUE TITLE
BUG: index out of range in months

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/FamilyFoto#174]
since v0.5.2
```sh
family-foto   | [2021-01-08 22:37:29,725] INFO in thumbnail_service: Generate thumbnail for IMG_20210107_122353_9.jpg
family-foto   | [2021-01-08 22:37:29,726] WARNING in image: Thumbnail already exists: /app/instance/photos/2e/2ed13b3533c529178e8f3478cf0b5eafec66cb4a3c7d80cf63c38ef8c025ae06/200_200_IMG_20210107_122353_9.jpg
family-foto   | [2021-01-08 22:37:29,730] ERROR in app: Exception on /public [GET]
family-foto   | Traceback (most recent call last):
family-foto   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
family-foto   |     response = self.full_dispatch_request()
family-foto   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
family-foto   |     rv = self.handle_user_exception(e)
family-foto   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
family-foto   |     reraise(exc_type, exc_value, tb)
family-foto   |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
family-foto   |     raise value
family-foto   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
family-foto   |     rv = self.dispatch_request()
family-foto   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
family-foto   |     return self.view_functions[rule.endpoint](**req.view_args)
family-foto   |   File "/usr/local/lib/python3.9/site-packages/prometheus_flask_exporter/__init__.py", line 686, in func
family-foto   |     return current_app.handle_user_exception(ex)
family-foto   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
family-foto   |     reraise(exc_type, exc_value, tb)
family-foto   |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
family-foto   |     raise value
family-foto   |   File "/usr/local/lib/python3.9/site-packages/prometheus_flask_exporter/__init__.py", line 684, in func
family-foto   |     raise exception
family-foto   |   File "/usr/local/lib/python3.9/site-packages/prometheus_flask_exporter/__init__.py", line 642, in func
family-foto   |     response = current_app.handle_user_exception(ex)
family-foto   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
family-foto   |     reraise(exc_type, exc_value, tb)
family-foto   |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
family-foto   |     raise value
family-foto   |   File "/usr/local/lib/python3.9/site-packages/prometheus_flask_exporter/__init__.py", line 639, in func
family-foto   |     response = f(*args, **kwargs)
family-foto   |   File "/app/family_foto/utils/protected.py", line 54, in is_active_wrapper
family-foto   |     return func(*args, **kwargs)
family-foto   |   File "/app/family_foto/utils/protected.py", line 28, in guest_user_wrapper
family-foto   |     return func(*args, **kwargs)
family-foto   |   File "/app/family_foto/web.py", line 211, in protected_gallery
family-foto   |     return render_template('gallery.html', user=current_user, years=years_sorted,
family-foto   |   File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
family-foto   |     return _render(
family-foto   |   File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
family-foto   |     rv = template.render(context)
family-foto   |   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
family-foto   |     self.environment.handle_exception()
family-foto   |   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
family-foto   |     reraise(*rewrite_traceback_stack(source=source))
family-foto   |   File "/usr/local/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
family-foto   |     raise value.with_traceback(tb)
family-foto   |   File "/app/family_foto/templates/gallery.html", line 1, in top-level template code
family-foto   |     {% extends "base.html" %}
family-foto   |   File "/app/family_foto/templates/base.html", line 39, in top-level template code
family-foto   |     {% block content %}{% endblock %}
family-foto   |   File "/app/family_foto/templates/gallery.html", line 15, in block "content"
family-foto   |     <h3>{{ month.month_name }}</h3>
family-foto   |   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 471, in getattr
family-foto   |     return getattr(obj, attribute)
family-foto   |   File "/app/family_foto/front_end_wrapper/month.py", line 32, in month_name
family-foto   |     return MONTH_NAMES[self.month]
family-foto   | IndexError: list index out of range
```

**Comment by Segelzwerg** [comment]
closed by #208
